# sensor params
sensor:
  image_dir: /home/autolab/Public/data/dex-net/data/gqcnn/abb/false_positive_2
  type: virtual_primesense
  frame: xtion_overhead
calib_dir: /home/autolab/Public/data/dex-net/data/gqcnn/abb

# policy params
policy:
  # gqcnn params
  gqcnn_model: /home/autolab/Public/data/dex-net/data/models/grasp_quality/gqcnn_vgg_dexnet_large_v1_01_24_17
  
  # optimization params
  num_seed_samples: 200
  num_gmm_samples: 50
  num_iters: 3
  gmm_refit_p: 0.25
  gmm_component_frac: 0.4
  gmm_reg_covar: 0.01

  # general params
  deterministic: 1
  gripper_width: 0.1
  crop_height: 96
  crop_width: 96

  # sampling params
  sampling:
    # type
    type: antipodal_depth

    # antipodality
    friction_coef: 1.0
    depth_grad_thresh: 0.01
    depth_grad_gaussian_sigma: 1.0
    downsample_rate: 4
    max_rejection_samples: 4000

    # distance
    max_dist_from_center: 1000
    min_dist_from_boundary: 45
    min_grasp_dist: 2.5
    angle_dist_weight: 5.0

    # depth sampling
    depth_samples_per_grasp: 1
    depth_sample_win_height: 1
    depth_sample_win_width: 1
    min_depth_offset: 0.015
    max_depth_offset: 0.05

  # visualization
  vis:
    grasp_sampling : 0
    tf_images: 0
    grasp_candidates: 1
    elite_grasps: 0
    grasp_ranking: 0
    grasp_plan: 1
    final_grasp: 1

    k: 25

# image proc params
inpaint_rescale_factor: 0.5
