# grasping params
num_grasp_samples: 25
gripper_width: 0.05
inpaint_rescale_factor: 0.5
visualize_sampling: 0

# sensor params
calib_dir: /home/autolab/Public/alan/calib
sensor:
  image_dir: data/rgbd/multiple_objects
  type: virtual_primesense
  frame: primesense_overhead

# sampling params
sampling:
  # antipodality
  friction_coef: 0.8
  depth_grad_thresh: 0.005
  depth_grad_gaussian_sigma: 1.0
  downsample_rate: 4
  max_num_attempts: 1000

  # distance
  max_dist_from_center: 120
  min_grasp_dist: 0.025
  angle_dist_weight: 0.025

  # depth sampling
  depth_samples_per_grasp: 1
  depth_sample_win_height: 1
  depth_sample_win_width: 1
  min_depth_offset: 0.015
  max_depth: 0.69
