# sensor params
sensor:
   #vvvvv here inputimage dir 
  image_dir: data/own #rgbd/multiple_objects

  type: virtual_primesense #realsense #virtual
  frame: primesense_overhead #primesense_overhead
calib_dir: data/calib

# policy params
policy:
  # optimization params
  num_seed_samples: 128
  num_gmm_samples: 64
  num_iters: 3
  gmm_refit_p: 0.25
  gmm_component_frac: 0.4
  gmm_reg_covar: 0.01

  # general params
  deterministic: 1
  gripper_width: 0.06

  # sampling param
  sampling:
    # type
    type: antipodal_depth
    # antipodality
    friction_coef: 1
    depth_grad_thresh: 0.025
    depth_grad_gaussian_sigma: 1
    downsample_rate: 2
    max_rejection_samples: 4000

    # distance
    max_dist_from_center: 160
    min_dist_from_boundary: 145
    min_grasp_dist: 2.5
    angle_dist_weight: 5.0

    # depth sampling
    depth_sampling_mode: uniform
    depth_samples_per_grasp: 1
    depth_sample_win_height: 1
    depth_sample_win_width: 1
    min_depth_offset:  0.015
    max_depth_offset:  0.05

  # metrics
  metric:
    type: gqcnn
    #vvvvv here model dir
    gqcnn_model: /home/jasy/GripperViewContainer/trained_models/GQ2017Paper-Grasp

    crop_height: 196
    crop_width: 196

  # visualization
  vis:
    grasp_sampling : 0
    tf_images: 0
    grasp_candidates: 1
    elite_grasps: 0
    grasp_ranking: 1
    grasp_plan: 0
    final_grasp: 1

    vmin: 0.5
    vmax: 0.8

    k: 25

# image proc params
inpaint_rescale_factor: 0.5
