# dataset params
dataset_dir: /home/autolab/Public/drive/projects/dex-net/data/grasp_quality/3dnet_kit_01_20_17
#dataset_dir: /home/autolab/Public/drive/projects/dex-net/data/grasp_quality/mini_dexnet_all_trans_01_20_17
output_dir: /home/autolab/Public/drive/projects/dex-net/data/models/grasp_quality

# training parameters
train_batch_size: 128
val_batch_size: 16
num_epochs: 15     # number of epochs to train fbor
eval_frequency: 5000  # how often to get validation error 
save_frequency: 5000  # how often to save output
vis_frequency: 5000
log_frequency: 1     # how often to log output
show_filters: 0

queue_capacity: 100  # capacity of prefetch queue
queue_sleep: 0.5     # how long to sleep between prefetches

train_pct: 0.8 # percentage of the data to use for training vs validation
total_pct: 1.0
eval_total_train_error: 0

optimizer: momentum
train_l2_regularizer: 0.0005
base_lr: 0.01
decay_step: 1000000   # step for exponential decay
decay_rate: 0.95
momentum_rate: 0.9
max_training_examples_per_load: 128

drop_fc6: 1
drop_fc7: 1

crane_grasps: 1

use_pretrained_weights: 0
pretrained_model_dir: /home/autolab/Public/drive/projects/dex-net/data/models/grasp_quality/gqcnn_vgg_kit_denoised_big_01_15_17
update_fc_only: 0
reinit_fc5: 0

image_mode: depth_tf_table
training_mode: classification
preproc_mode: none
num_tensor_channels: 1
pos_weight: 0.1

num_random_files: 100

target_metric_name: robust_ferrari_canny
metric_thresh: 0.002

#target_metric_name: human_label
#metric_thresh: 0

# architecture
architecture:
  conv1_1:
    filt_dim: 7
    num_filt: 64
    pool_size: 1
    pool_stride: 1  
    norm: 0
  conv1_2:
    filt_dim: 5
    num_filt: 64
    pool_size: 2
    pool_stride: 2
    norm: 1
  conv2_1:
    filt_dim: 3
    num_filt: 64
    pool_size: 1
    pool_stride: 1
    norm: 0
  conv2_2:
    filt_dim: 3
    num_filt: 64
    pool_size: 1
    pool_stride: 1
    norm: 1
  pc1:
    out_size: 16
  pc2:
    out_size: 0
  fc3:
    out_size: 1024
  fc4:
    out_size: 1024
  fc5:
    out_size: 2

# denoising / synthetic data
multiplicative_denoising: 1
gamma_shape: 1000.00

symmetrize: 1

morphological: 0
morph_open_rate: 0.25
morph_poisson_mean: 1.5

image_dropout: 0
image_dropout_rate: 0.25
dropout_poisson_mean: 1.0
dropout_radius_shape: 3.0
dropout_radius_scale: 1.0

gradient_dropout: 0
gradient_dropout_rate: 0.1
gradient_dropout_sigma: 0.5
gradient_dropout_shape: 15
gradient_dropout_scale: 0.001

gaussian_process_denoising: 1
gaussian_process_rate: 0.5
gaussian_process_scaling_factor: 4.0
gaussian_process_sigma: 0.005

border_distortion: 0
border_grad_sigma: 1.0
border_grad_thresh: 0.075
border_poisson_mean: 5.0
border_radius_shape: 5
border_radius_scale: 0.4

background_denoising: 0
background_rate: 0.25
background_min_depth: 0.0
background_max_depth: 0.65

# debugging params
debug: 0
debug_num_files: 300